### PR TITLE
Minor updates to README.md and package.json

### PR DESCRIPTION
**Pull request by ilonabudapesti**
I put these two comments in their own PR so you can merge them in and ignore my platform specific changes.

### CODE REVIEW

**Comment by zoltanctoth** [comment]
@monthypython That's great! Thanks for your contribution!

**Comment by ilonabudapesti** [comment]
@zoltanctoth  Thanks for accepting and sorry for the trouble earlier.

I am about to get started with the TODOs on plotserver. Could you add
a little more detail to the tasks when you have time? Thanks.

**Comment by zoltanctoth** [comment]
TODO's = issues?
btw do you use it for your own or for a company? We are interested to see who uses it

**Comment by zoltanctoth** [comment]
Ah, I get the TODOs

refactor client.html -> i don't know, maybe ugly. @mtrencseni ?
prettify the client -> design mockup
replace Google charts with d3.js -> it'd be nice to use highcharts/d3 for the rendering, but it is a bigger job. Right now we use the Google Charting API
add support for dashboards -> click around and create dashboards, or make a dashboard specification in i.e. json: what charts are embedded in which size/cordinates. I think we will work in it at some point of the time
add support for large datasets -> @mtrencseni 
add Mysql backend -> the main idea here is to ha the charts stored in SQL. So we can execute SQL queries and i.e. display daily aggregates of data.

**Comment by ilonabudapesti** [comment]
I meant the TODO list at the bottom of the README.md

I work at PayPal. If you know about Kraken.JS I am in one of the teams
that builds the app entirely in Node. I am interested in plotserver to
plot our log data.

How do you use it at Prezi? Do you have a detailed use-case e.g a blog?

**Comment by ilonabudapesti** [comment]
Oops, our mails just crossed. You are either working late, or you are
perhaps on European time.
1. You found the todos. Great.
2. refactor client.html - @mtrencseni. Were you thinking of moving the
   javascript and jquery out of the html tags into their own js files or is
   there something else too?
3. d3: yes, it seems like a bigger job but I might get to it too if
   plotserver gains popularity in the team.
4. dashboard: got it. I think this is a priority item. Could I move it to
   the top?
5. large datasets: @mtrencseni do you have a more specific number that you
   consider large?
6. Mysql backend: interesting. Since we don't have any mysql in the app I
   am working on I would prefer to have a nosql backend, specifically mongodb.
   I am going to explore this idea in a separate branch and let you know. But
   making sql queries available is a good idea I can see the uses.

I would also like to add some todos, if it's OK.
1. send notification: allow the definition of rules for certain key-value
   pairs, and when a value is triggered (<, >, =, != etc.) then send email
   notification
2. automation: set periodical jobs where plotserver pulls from the (log)
   data and plots
3. screenshot: take screenshot and email it

Koszonom.

**Pull request merged**
